play.http.secret.key=${?APPLICATION_SECRET}

play.filters.disabled += play.filters.hosts.AllowedHostsFilter

play.modules.enabled += "modules.BindingModule"

db.default.driver=org.postgresql.Driver
db.default.url=${?POSTGRES_URL}
db.default.username=${?POSTGRES_USER}
db.default.password=${?POSTGRES_PASSWORD}
db.default.jndiName=DefaultDS

jpa.default=defaultPersistenceUnit

play.evolutions {
    autoApply = true
}